
### ruff
[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py310"

[tool.ruff.format]
preview = true
quote-style = "double" # "single"
indent-style = "space" # "tab"


### basedpyright
[tool.basedpyright]
typeCheckingMode = 'standard' # "off", "basic", "standard", "strict", "all"
reportAny = false

[[tool.basedpyright.executionEnvironments]]
root = "scripts"
extraPaths = [
    "deps/repos/Vulkan-ValidationLayers/scripts",
    "deps/x64-mingw-mix/share/vulkan/registry",
]
