#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(binding = 0, rgba32f) readonly uniform image2D inp_img;
layout(binding = 1, rgba32f) writeonly uniform image2D out_img;
layout(push_constant) uniform Args {
    int scaler;
} args;

layout(constant_id = 0) const int alpha = 1;

void main() {
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    vec3 color = imageLoad(inp_img, pos).rgb;
    imageStore(out_img, pos, vec4(color * args.scaler, float(alpha)));
}
