# x64-mingw-mix

cmake_minimum_required(VERSION 3.5)

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME MinGW)

# set(VCPKG_KEEP_ENV_VARS PATH)
set(VCPKG_ENV_PASSTHROUGH_UNTRACKED PATH)

if(PORT STREQUAL "imgui")
    set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -DIMGUI_IMPL_VULKAN_NO_PROTOTYPES")
    set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} -DIMGUI_IMPL_VULKAN_NO_PROTOTYPES")
endif()

set(DEPS_DYNAMIC assimp)
if((PORT IN_LIST DEPS_DYNAMIC) OR (PORT MATCHES "^qt-.*"))
    # Dynamic
    set(VCPKG_LIBRARY_LINKAGE dynamic)
    set(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
else()
    # Static
    set(VCPKG_LIBRARY_LINKAGE static)
endif()

